credentials:
  usernames:
    admin:
      email: teste@teste.com
      logged_in: False
      name: admin
      password: admin
    
    pessoal:
      email: rh@produmar.ind.br
      logged_in: False
      name: Grécia
      password: rhpessoal
      
cookie:
  expiry_days: 1
  key: some_signinature_key
  name: some_cookie_name